CREATE TABLE CSVREADWRITE(FILENAME VARCHAR(255), ORIGIN VARCHAR(255), METADATA VARCHAR(255), HASH VARCHAR(255))
    AS SELECT * FROM CSVREAD('C:/Users/maxwe/Downloads/ac56fe111.csv');

    ALTER TABLE CSVREADWRITE ADD id int auto_increment;